# Generated by Django 5.1.7 on 2025-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_card_category_order_product_card_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
