# Generated by Django 5.1.7 on 2025-04-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(default='immage', upload_to='category/'),
        ),
    ]
